#!/bin/bash

cp -aru ../IPCC_AR6_CH11/cmip_indices_regional/indices_multi_model_median/csv/* indices/csv/
cp -aru ../IPCC_AR6_CH11/cmip_indices_regional/indices_multi_model_median/md/* indices/md/
cp -aru ../IPCC_AR6_CH11/cmip_indices_regional/indices_multi_model_median/data_tables/*[!raw] indices/data_tables/
cp -aru ../IPCC_AR6_CH11/cmip_indices_regional/indices_all_models_one_ens/csv/* indices_all_models_one_ens/csv/
